### ISSUE TITLE
Android app is not building

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [Hopding/react-native-pdf-lib#32] opened 2018-10-30 13:57 UTC
:react-native-pdf-lib:processDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-pdf-lib:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by Hopding** [comment] 2018-11-05 17:44
Closing this as it is a duplicate of https://github.com/Hopding/react-native-pdf-lib/issues/27. A workaround can be found in that thread.

**Closed by Hopding** 2018-11-05 17:44 UTC
