### ISSUE TITLE
Set variable to text undefined ?

### ISSUE THREAD

**Issue by hieuluis96** [Hopding/react-native-pdf-lib#21] opened 2018-06-27 07:10 UTC
Hi, your library was be useful for my project that i had been working, but when i went to set text from variable, it  displayed "undefined ". My code look like 👍 

```
cretePDF
 = ({name}) => () => {
const fs = RNFetchBlob.fs;
const dirs = fs.dirs;
// Create page
const page1 = PDFPage.create()
.setMediaBox(Dimensions.get('window').width, Dimensions.get('window').height)
.drawRectangle({
x: 0,
y: Dimensions.get('window').height - 100,
width: Dimensions.get('window').width,
color: '#eaff0a',
height: 100,
})
.drawText(`${name}`, {
x: Dimensions.get('window').width / 2,
y: Dimensions.get('window').height - 16,
fontSize: 16
})
const path = `${dirs.DownloadDir}/SAMPLE.pdf`;
PDFDocument.create(path).addPage(page1).write().then((res) => {
console.log("File saved at: " + res);
})
}
```
Result:
![image](https://user-images.githubusercontent.com/40381681/41958673-f799177a-7a14-11e8-8a95-9531cbd1fdb6.png)

Thank you for reply

**Comment by Hopding** [comment] 2018-06-27 21:38
Based on the code you've provided here, it looks like the `name` variable passed to `drawText` must be `undefined`:
```javascript
...
.drawText(`${name}`, {
  x: Dimensions.get('window').width / 2,
  y: Dimensions.get('window').height - 16,
  fontSize: 16
})
...
```
Have you verified what value it contains?

**Comment by hieuluis96** [comment] 2018-06-28 01:52
Yes I had create function to using with variable i had. Ex: 
render(){
let name = "Kevin"
return (
<Button
...
onPress={()=>createPDF(name)}
/>
)
}
But still undefined when i open pdf

**Comment by Hopding** [comment] 2018-06-29 21:57
If you can provide a complete code snippet, I can try to reproduce the problem. Unfortunately, from the partial snippets you've shared thus far, it's not clear to me where the problem lies.

**Comment by Hopding** [comment] 2018-07-13 01:19
I'm going to close this. Feel free to reopen if you're still encountering a problem.

**Closed by Hopding** 2018-07-13 01:19 UTC
