### ISSUE TITLE
Build failure on Android

### ISSUE THREAD

**Issue by martnst** [Hopding/react-native-pdf-lib#27] opened 2018-07-26 14:36 UTC
I am encountering a build error on Android.

**steps:**

- `react-native init RNPDFPlay`
- `cd RNPDFPlay`
- `yarn add react-native-pdf-lib`
- add `dexOptions { jumboMode = true }` to `./android/app/build.gradle`
- `react-native run-android`

**build log:**
```
:react-native-pdf-lib:processReleaseResources
.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

.../RNPDFPlay/node_modules/react-native-pdf-lib/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


:react-native-pdf-lib:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pdf-lib:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**env:**
- macOS: 10.13.4
```
$ react-native --version       
react-native-cli: 2.0.1
react-native: 0.56.0
```

**Comment by martnst** [comment] 2018-07-26 15:15
Setting up with the same steps but using react-native 0.55 via [rninit](https://github.com/jacobbubu/rninit) `react-native init` instead works fine.

**Comment by Hopding** [comment] 2018-10-17 15:00
Hello @martnst. Thanks for reporting this issue! 

My apologies for the late response. I'm afraid I don't have the time to debug or fix this issue right now. But I suspect that it is caused by the `minSdkVersion`, `compileSdkVersion`, `targetSdkVersion`, or `buildToolsVersion` being incorrect for React Native `0.56+`. 

I think this could be fixed by updating these values. Or, even better, not hardcoding those values, and instead relying on those defined in the parent project. PRs for this are welcomed :)

In the meantime, you can add the following to your `android/build.gradle` file to force your dependencies to use the same `compileSdkVersion` and `buildToolsVersion` values as your main project:
```gradle
/**
 * Force dependencies to use the same compileSdk and buildTools versions as the main project.
 *
 * Source: https://stackoverflow.com/a/25736483
 */
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

```
I'm not a gradle expert, but I'm sure you could change this script to only target `react-native-pdf-lib`.

**Comment by martnst** [comment] 2018-10-20 08:52
Hi @Hopding, okay fair enough. I actually ended up going a different way via some own native code turning HTML into PDF. If I remember right I kinda just wanted to report this FYI.

**Comment by georgewwindsor** [comment] 2019-03-20 12:35
@Hopding , that worked for me thanks

**Comment by thekevinbrown** [comment] 2020-02-09 23:51
I'll go ahead and close this issue as v1.0.0 should help here, and if not, this workaround should help too. If anyone knows of a better way we can tackle this please feel free to open a PR.

**Closed by thekevinbrown** 2020-02-09 23:51 UTC
