### ISSUE TITLE
Attempt to invoke virtual method 'Int android.graphics.Bitmap.getWidth()' on a null object ref

### ISSUE THREAD

**Issue by MSH786** [Hopding/react-native-pdf-lib#85] opened 2021-04-09 12:07 UTC
hi, when i run code, 

then i get error, attach screenshot

here is my code

import React from 'react';
import type {Node} from 'react';
import {
  SafeAreaView,TouchableOpacity,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import PDFLib, { PDFDocument, PDFPage } from 'react-native-pdf-lib';

const App=() => {
 
const generate=async()=>{

 const page1 = PDFPage
  .create()
  .setMediaBox(200, 200)
  .drawText('You can add text and rectangles to the PDF!', {
    x: 5,
    y: 235,
    color: '#007386',
  })
  .drawRectangle({
    x: 25,
    y: 25,
    width: 150,
    height: 150,
    color: '#FF99CC',
  })
  .drawRectangle({
    x: 75,
    y: 75,
    width: 50,
    height: 50,
    color: '#99FFCC',
  });

// Create a PDF page with text and images
const jpgPath = "https://commons.wikimedia.org/wiki/File:Sunflower_from_Silesia2.jpg"// Path to a JPG image on the file system...
const pngPath = "https://www.freepik.com/free-photos-vectors/png"// Path to a PNG image on the file system...
const page2 = PDFPage
  .create()
  .setMediaBox(250, 250)
  .drawText('You can add JPG images too!')
  .drawImage(jpgPath, 'jpg', {
     x: 5,
     y: 125,
     width: 200,
     height: 100,
  })
  .drawImage(pngPath, 'png', {
     x: 5,
     y: 25,
     width: 200,
     height: 100,
  });

    // Create a new PDF in your app's private Documents directory
    const docsDir = await PDFLib.getDocumentsDirectory();
    const pdfPath = `${docsDir}/sample.pdf`;
    PDFDocument
      .create(pdfPath)
      .addPages(page1, page2)
      .write() // Returns a promise that resolves with the PDF's path
      .then(path => {
        console.log('PDF created at: ' + path);
        // Do stuff with your shiny new PDF!
      });
  }

  return (
          <TouchableOpacity onPress={()=>{ generate() }} >
          <View>
            <Text>
              Generate Pdf now
            </Text>
          </View>
          </TouchableOpacity>
  );
};

export default App;
![WhatsApp Image 2021-04-09 at 5 03 06 PM](https://user-images.githubusercontent.com/58289501/114177619-0da3ae00-9956-11eb-8ed4-a46b5768269a.jpeg)

**Comment by MSH786** [comment] 2021-04-09 12:08
OR this issue facing becuase of images over internet

I am trying with file system after that revert back to you

**Comment by MSH786** [comment] 2021-04-09 13:23
This issue remain with file system 

i have used image picker library but remain same

**Comment by JavierLaguna** [comment] 2021-04-20 09:41
I have the same issue, any update?

**Comment by MSH786** [comment] 2021-04-21 15:00
ok i will use check and revert back to

> I have the same issue, any update?
> 
> EDIT:
> @MSH786 worked for me removing `file://` from the file system images path, try it!

OK, i will check and revert back to you .

Thank You

**Comment by rlov** [comment] 2021-05-09 01:46
I have the same issue :c

**Comment by thekevinbrown** [comment] 2021-06-26 02:10
Alright, as I can't reproduce I'll close this issue. If this is still a problem please open up a new issue with a reproduction repository and I'd be happy to have a look.

**Closed by thekevinbrown** 2021-06-26 02:10 UTC

**Comment by nishant-BabyG** [comment] 2024-03-13 06:58
> I have the same issue, any update?
> 
> EDIT: @MSH786 worked for me removing `file://` from the file system images path, try it!

this worked for me for the package 'react-native-image-to-pdf'

**Comment by Nihalkottakkal** [comment] 2024-05-12 21:02
> > I have the same issue, any update?
> > EDIT: @MSH786 worked for me removing `file://` from the file system images path, try it!
> 
> this worked for me for the package 'react-native-image-to-pdf'

Hi,
could you please help me with this issue ??

**Comment by nishant-BabyG** [comment] 2024-05-13 16:23
> > > I have the same issue, any update?
> > > EDIT: @MSH786 worked for me removing `file://` from the file system images path, try it!
> > 
> > 
> > this worked for me for the package 'react-native-image-to-pdf'
> 
> Hi, could you please help me with this issue ??

if it's ios keep "file://" else remove it for android.
