### ISSUE TITLE
App crashes when modifying PDF

### ISSUE THREAD

**Issue by Laurein** [Hopding/react-native-pdf-lib#40] opened 2019-03-15 00:22 UTC
App crashes when trying to modify PDF file. I'm modifying pdf on a press of a button. I attached code to this issue. 
```
import React, { Component } from "react";
import { View, Text, Button } from "react-native";
import PDFLib, { PDFDocument, PDFPage } from "react-native-pdf-lib";

class Test extends Component {
  modifyPDF = () => {
    // Modify first page in document
    const page1 = PDFPage.modify(0)
      .drawText("This is a modification on the first page!", {
        x: 5,
        y: 235,
        color: "#F62727"
      })
      .drawRectangle({
        x: 150,
        y: 150,
        width: 50,
        height: 50,
        color: "#81C744"
      });

    const existingPDF =
      "absolute/path/to/my/pdf";
    PDFDocument.modify(existingPDF)
      .modifyPages(page1)
      .write() // Returns a promise that resolves with the PDF's path
      .catch(err => {
        console.log(err);
      })
      .then(path => {
        console.log("PDF modified at: " + path);
      });
  };

  render() {
    return (
      <View>
        <Button title="La" onPress={() => this.modifyPDF()} />
      </View>
    );
  }
}

export default Test;
```

**Comment by Hopding** [comment] 2019-03-23 14:07
@Laurein What is the stacktrace/error you get when the app crashes?

**Comment by Hopding** [comment] 2019-05-02 22:44
I'm going to close this issue for now. But please feel free to reopen it if you have additional questions!

**Closed by Hopding** 2019-05-02 22:44 UTC

**Comment by lunajing** [comment] 2020-05-21 08:02
> modifyPDF

did you solve this problem?

error msg "TypeError: null is not an object (evaluating '_PDFLib.default.modifyPDF')" ?

**Comment by AbdallahRahal** [comment] 2020-06-15 16:26
I have this Error to is there a solution ?

**Comment by vipulswarup** [comment] 2020-06-25 07:30
I have the same error. There is no stack trace. Below is the error message.

`[TypeError: null is not an object (evaluating '_PDFLib.default.modifyPDF')]`

**Comment by AbhishekNairOfficial** [comment] 2020-07-02 11:56
> > modifyPDF
> 
> did you solve this problem?
> 
> error msg "TypeError: null is not an object (evaluating '_PDFLib.default.modifyPDF')" ?

I have the same issue too. Is there a dependency that we're missing?

**Comment by p-c-daniel** [comment] 2020-09-15 12:25
Any news regarding this issue?

**Comment by thekevinbrown** [comment] 2020-09-16 00:51
I suspect it's a linking issue, but I have not reproduced, so this is just a hunch.

If something in the library needs to change, pull requests are welcome.

**Comment by ssalcedo-gnt** [comment] 2021-03-26 19:25
Did someone fix the issue?

**Comment by AnasAlamin** [comment] 2021-11-05 12:07
how come this issue is closed?!, we've been facing this issue for a while now!

**Comment by thekevinbrown** [comment] 2021-11-08 00:03
The issue is closed because I haven't been able to reproduce it. Could you provide a reproduction project @AnasAlamin?

**Comment by reactnative94** [comment] 2022-01-03 14:14
const page1 = PDFPage
  .modify(0)
  .drawText('This is a modification on the first page!', {
    x: 5,
    y: 235,
    color: '#F62727',
  })

As given in the above code PDFPage.modify() there is no modify method linked to PDFPage class. when I hover to PDFPage below is the code.

export class PDFPage {
    static create(): PDFPage;

    setMediaBox(width: number, height: number, options?: SetMediaBoxOptions): PDFPage;

    drawText(text: string, options?: TextDrawingOptions): PDFPage;
    drawRectangle(options?: RectangleDrawingOptions): PDFPage;
    drawImage(imageUri: string, options?: ImageDrawingOptions): PDFPage;
}

So how modify method is accessible?
