### ISSUE TITLE
pages 6 added android v 6 around 50 sec time get and ios side only 10 sec get why 

### ISSUE THREAD

**Issue by appa3151** [Hopding/react-native-pdf-lib#55] opened 2019-09-17 11:29 UTC

**Comment by thekevinbrown** [comment] 2019-10-25 06:22
The library uses different underlying PDF implementations on each platform. The iOS one is generally faster than the Android one, plus it depends on the performance characteristics of the Android device you're using.

We're creating 120 page print quality PDFs in our app, and a Galaxy S9 is about 3 times faster than a Motorola G7 because it's a processor intensive task.

I imagine PRs would be welcome to improve the Android performance if you can do some work to optimise it.

**Comment by thekevinbrown** [comment] 2020-02-09 23:55
This looks like a duplicate of #48 to me. I'll close this one so we can track the conversation there.

**Closed by thekevinbrown** 2020-02-09 23:55 UTC
